### ISSUE TITLE
Permissions page available for support users

### ISSUE THREAD

**Issue by anderslarssonvbg** [freeacs/web#7]
Hi

The permissions page in the top menu is available for users who has "modules" set to only WEB[Support].

That could be ok if you would only see other users with only access to the same module. But you can actually see all other users which aren't "admin".

You can also create new users with access to other modules, e.g. to "full provisioning".

It's also possible to choose that the new user should be "Admin", but that seems to be restricted cause the new user isn't set as admin.

All in all, this means that a user which low permissions could create a new user with more permissions.

My personal opinion is that only users which is admin should have access the permission page, but I guess there could be reasons why that is not the case.

-- Anders

**Comment by jarlah** [comment]
I have made a sort of quick and dirty solution to hide the permissions page for non admin users, but I am not sure if this is correct behaviour. In my view a user that is not admin should not be able to add new users. But as Morten commented, maybe it should be possible for same access level? Anyway the latter is a feature request.

**Comment by jarlah** [comment]
I have made a pull request which makes it so that only admins get access to permissions page. The users who is either with username "admin" or have the admin property set to true. Which then makes it up to communication with server administrator or acs administrator to figure out why a certain person can't see the modules he need to see. E.g. he should not be able to enter the permissions page himself to check.
